version: '3.8'

services:
  backend:
    image: ghcr.io/bagasstr/api-matrakosala:1.8
    restart: always
    networks:
      - ix-cloudflared_default
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5100:5100'
    volumes:
      - /mnt/nas/docker-data/files_uploads/image:/app/public/upload/image
      - /mnt/nas/docker-data/files_uploads/document:/app/public/upload/document
    environment:
      DATABASE_URL: 'postgresql://postgres:root@postgres_db:5432/postgres?schema=public'
      NODE_ENV: production
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    networks:
      - ix-cloudflared_default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - /mnt/nas/docker-data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
    driver: local
networks:
  ix-cloudflared_default:
    external: true
    name: ix-cloudflared_default
